/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.ClienteDAO;
import biblioteca.Cliente;
import java.awt.Image;
import javax.swing.JOptionPane;

/**
 *
 * @author izael
 */
public class AreaCliente extends javax.swing.JFrame {

    /**
     * Creates new form AreaCliente
     */
    public AreaCliente() {
        initComponents();
    }
    
    public Image tempGetImg(){
        
        javax.swing.ImageIcon imageIcon = new javax.swing.ImageIcon(getClass().getResource("/icons/temor.jpg")); // load the image to a imageIcon
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(105, 150,  java.awt.Image.SCALE_SMOOTH);
        return newimg;
        
    }
    
    public void setCltLogin(Cliente cliente){
        ClienteDAO clt = new ClienteDAO();
        clt.dadosUsuario(cliente);
        /*
        jLabelLogin.setText(cliente.getLogin());
        jLabelNome.setText(cliente.getNome());
        jLabelCpf.setText(cliente.getCpf());
        jLabelEmail.setText(cliente.getEmail());
        jLabelDataNasc.setText(cliente.getData_nasc());
        jLabelContato.setText(cliente.getData_nasc());
        */
        }
    
    public void bemVindo(){
        JOptionPane.showMessageDialog(null, "Seja bem-vindo "/*+jLabelNome.getText()*/);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabelGerenciamento = new javax.swing.JLabel();
        jSeparatorGer = new javax.swing.JSeparator();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jLabelPesquisa = new javax.swing.JLabel();
        jSeparatorPes = new javax.swing.JSeparator();
        jButtonConteudoHistorico = new javax.swing.JButton();
        jButtonAventura = new javax.swing.JButton();
        jButtonSuspense = new javax.swing.JButton();
        jButtonTerror = new javax.swing.JButton();
        jButtonRomance = new javax.swing.JButton();
        jButtonEducacional = new javax.swing.JButton();
        jButtonComedia = new javax.swing.JButton();
        jLabelCategoria = new javax.swing.JLabel();
        jSeparatorCat = new javax.swing.JSeparator();
        jButtonPerfil = new javax.swing.JButton();
        jButtonLivrosAlugados = new javax.swing.JButton();
        jButtonHistorico = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanelTelaInicial = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelLivro1 = new javax.swing.JLabel();
        jLabelTitLivro1 = new javax.swing.JLabel();
        jLabelLivro2 = new javax.swing.JLabel();
        jLabelTitLivro2 = new javax.swing.JLabel();
        jLabelLivro3 = new javax.swing.JLabel();
        jLabelTitLivro3 = new javax.swing.JLabel();
        jLabelLivro4 = new javax.swing.JLabel();
        jLabelTitLivro4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelLivro5 = new javax.swing.JLabel();
        jLabelTitLivro5 = new javax.swing.JLabel();
        jLabelLivro6 = new javax.swing.JLabel();
        jLabelTitLivro6 = new javax.swing.JLabel();
        jLabelLivro7 = new javax.swing.JLabel();
        jLabelTitLivro7 = new javax.swing.JLabel();
        jLabelLivro8 = new javax.swing.JLabel();
        jLabelTitLivro8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(57, 57, 57));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(67, 67, 67));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelGerenciamento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelGerenciamento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGerenciamento.setText("Gerenciamento");
        jPanel1.add(jLabelGerenciamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 170, 30));
        jPanel1.add(jSeparatorGer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 170, 10));
        jPanel1.add(jTextFieldPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, 170, -1));

        jLabelPesquisa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPesquisa.setText("Pesquisa");
        jPanel1.add(jLabelPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 170, 30));
        jPanel1.add(jSeparatorPes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 170, 10));

        jButtonConteudoHistorico.setForeground(new java.awt.Color(90, 95, 98));
        jButtonConteudoHistorico.setText("Conteudo Histórico");
        jButtonConteudoHistorico.setBorderPainted(false);
        jPanel1.add(jButtonConteudoHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 170, 20));

        jButtonAventura.setForeground(new java.awt.Color(90, 95, 98));
        jButtonAventura.setText("Aventura");
        jButtonAventura.setBorderPainted(false);
        jPanel1.add(jButtonAventura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 170, 20));

        jButtonSuspense.setForeground(new java.awt.Color(90, 95, 98));
        jButtonSuspense.setText("Suspense");
        jButtonSuspense.setBorderPainted(false);
        jPanel1.add(jButtonSuspense, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 170, 20));

        jButtonTerror.setForeground(new java.awt.Color(90, 95, 98));
        jButtonTerror.setText("Terror");
        jButtonTerror.setBorderPainted(false);
        jPanel1.add(jButtonTerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 170, 20));

        jButtonRomance.setForeground(new java.awt.Color(90, 95, 98));
        jButtonRomance.setText("Romance");
        jButtonRomance.setBorderPainted(false);
        jPanel1.add(jButtonRomance, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 170, 20));

        jButtonEducacional.setForeground(new java.awt.Color(90, 95, 98));
        jButtonEducacional.setText("Educacional");
        jButtonEducacional.setBorderPainted(false);
        jPanel1.add(jButtonEducacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 170, 20));

        jButtonComedia.setForeground(new java.awt.Color(90, 95, 98));
        jButtonComedia.setText("Comédia");
        jButtonComedia.setBorderPainted(false);
        jPanel1.add(jButtonComedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 170, 20));

        jLabelCategoria.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCategoria.setText("Categorias");
        jPanel1.add(jLabelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 30));
        jPanel1.add(jSeparatorCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 10));

        jButtonPerfil.setForeground(new java.awt.Color(90, 95, 98));
        jButtonPerfil.setText("Meu Perfil");
        jButtonPerfil.setBorderPainted(false);
        jButtonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 170, 20));

        jButtonLivrosAlugados.setForeground(new java.awt.Color(90, 95, 98));
        jButtonLivrosAlugados.setText("Livros Alugados");
        jButtonLivrosAlugados.setActionCommand("");
        jButtonLivrosAlugados.setBorderPainted(false);
        jButtonLivrosAlugados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLivrosAlugadosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLivrosAlugados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 170, 20));

        jButtonHistorico.setForeground(new java.awt.Color(90, 95, 98));
        jButtonHistorico.setText("Histórico");
        jButtonHistorico.setBorderPainted(false);
        jPanel1.add(jButtonHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 170, 20));

        jButtonLogout.setForeground(new java.awt.Color(90, 95, 98));
        jButtonLogout.setText("Logout");
        jPanel1.add(jButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 70, 30));

        jPanel2.setLayout(new java.awt.CardLayout());

        jPanelTelaInicial.setBackground(new java.awt.Color(204, 204, 255));
        jPanelTelaInicial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLivro1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLivro1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLivro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLivro1.setIcon(new javax.swing.ImageIcon(tempGetImg()));
        jLabelLivro1.setToolTipText("");
        jLabelLivro1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabelTitLivro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitLivro1.setText("O Temor do Sábio");

        jLabelLivro2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLivro2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLivro2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLivro2.setIcon(new javax.swing.ImageIcon(tempGetImg()));
        jLabelLivro2.setToolTipText("");
        jLabelLivro2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabelTitLivro2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitLivro2.setText("O Temor do Sábio");

        jLabelLivro3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLivro3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLivro3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLivro3.setIcon(new javax.swing.ImageIcon(tempGetImg()));
        jLabelLivro3.setToolTipText("");
        jLabelLivro3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabelTitLivro3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitLivro3.setText("O Temor do Sábio");

        jLabelLivro4.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLivro4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLivro4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLivro4.setIcon(new javax.swing.ImageIcon(tempGetImg()));
        jLabelLivro4.setToolTipText("");
        jLabelLivro4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabelTitLivro4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitLivro4.setText("O Temor do Sábio");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelLivro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTitLivro1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelLivro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTitLivro2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelLivro3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTitLivro3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelLivro4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTitLivro4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelLivro4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelTitLivro4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelLivro3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelTitLivro3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelLivro2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelTitLivro2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelLivro1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelTitLivro1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanelTelaInicial.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 500, 170));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Recomendado para Você!");
        jPanelTelaInicial.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 30));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanelTelaInicial.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 310, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanelTelaInicial.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 310, 10));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Lançamentos");
        jPanelTelaInicial.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 320, 30));

        jLabelLivro5.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLivro5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLivro5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLivro5.setIcon(new javax.swing.ImageIcon(tempGetImg()));
        jLabelLivro5.setToolTipText("");
        jLabelLivro5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabelTitLivro5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitLivro5.setText("O Temor do Sábio");

        jLabelLivro6.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLivro6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLivro6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLivro6.setIcon(new javax.swing.ImageIcon(tempGetImg()));
        jLabelLivro6.setToolTipText("");
        jLabelLivro6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabelTitLivro6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitLivro6.setText("O Temor do Sábio");

        jLabelLivro7.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLivro7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLivro7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLivro7.setIcon(new javax.swing.ImageIcon(tempGetImg()));
        jLabelLivro7.setToolTipText("");
        jLabelLivro7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabelTitLivro7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitLivro7.setText("O Temor do Sábio");

        jLabelLivro8.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLivro8.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLivro8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLivro8.setIcon(new javax.swing.ImageIcon(tempGetImg()));
        jLabelLivro8.setToolTipText("");
        jLabelLivro8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabelTitLivro8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitLivro8.setText("O Temor do Sábio");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelLivro5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTitLivro5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelLivro6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTitLivro6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelLivro7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTitLivro7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelLivro8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTitLivro8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelLivro8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelTitLivro8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelLivro7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelTitLivro7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelLivro6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelTitLivro6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelLivro5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelTitLivro5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanelTelaInicial.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 500, 170));

        jPanel2.add(jPanelTelaInicial, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPerfilActionPerformed

    private void jButtonLivrosAlugadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLivrosAlugadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLivrosAlugadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAventura;
    private javax.swing.JButton jButtonComedia;
    private javax.swing.JButton jButtonConteudoHistorico;
    private javax.swing.JButton jButtonEducacional;
    private javax.swing.JButton jButtonHistorico;
    private javax.swing.JButton jButtonLivrosAlugados;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonPerfil;
    private javax.swing.JButton jButtonRomance;
    private javax.swing.JButton jButtonSuspense;
    private javax.swing.JButton jButtonTerror;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelGerenciamento;
    private javax.swing.JLabel jLabelLivro1;
    private javax.swing.JLabel jLabelLivro2;
    private javax.swing.JLabel jLabelLivro3;
    private javax.swing.JLabel jLabelLivro4;
    private javax.swing.JLabel jLabelLivro5;
    private javax.swing.JLabel jLabelLivro6;
    private javax.swing.JLabel jLabelLivro7;
    private javax.swing.JLabel jLabelLivro8;
    private javax.swing.JLabel jLabelPesquisa;
    private javax.swing.JLabel jLabelTitLivro1;
    private javax.swing.JLabel jLabelTitLivro2;
    private javax.swing.JLabel jLabelTitLivro3;
    private javax.swing.JLabel jLabelTitLivro4;
    private javax.swing.JLabel jLabelTitLivro5;
    private javax.swing.JLabel jLabelTitLivro6;
    private javax.swing.JLabel jLabelTitLivro7;
    private javax.swing.JLabel jLabelTitLivro8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelTelaInicial;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparatorCat;
    private javax.swing.JSeparator jSeparatorGer;
    private javax.swing.JSeparator jSeparatorPes;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables
}
