package view;

import DAO.UsuarioDAO;
import biblioteca.Usuario;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AreaUsuario extends javax.swing.JFrame {
    
    public AreaUsuario() {
        initComponents();
        setCbCargos();
        setCbAltDelCargos();
        listarTabela();
    }
    
    //Adiciona as opções de Cargos na ComboBox de Cadastro de Usuários
    public void setCbCargos(){
        jCbCargo.removeAllItems();
        jCbCargo.addItem("-");
        jCbCargo.addItem("Administrador");
        jCbCargo.addItem("Bibliotecário");
    }
    
    //Adiciona as opções de Cargos na ComboBox de Alt/Del Usuários
    public void setCbAltDelCargos(){
        jCbAltDelCargo.removeAllItems();
        jCbAltDelCargo.addItem("-");
        jCbAltDelCargo.addItem("Administrador");
        jCbAltDelCargo.addItem("Bibliotecário");
    }
    
    //Pega os dados do Usuários e inclui no JFrame
    public void setUsLogin(Usuario usuario){
        UsuarioDAO us = new UsuarioDAO();
        us.dadosUsuario(usuario);
        jLabelId.setText(String.valueOf(usuario.getId_usuario()));
        jLabelLogin.setText(usuario.getLogin());
        jLabelNome.setText(usuario.getNome());
        jLabelCpf.setText(usuario.getCpf());
        jLabelEmail.setText(usuario.getEmail());
        jLabelCargo.setText(usuario.getCargo());
    }
    
    //Validação de Usuário, se é ou não Administrador (habilita/desabilita Ger. Usuários)
    public void validaAdm(boolean x){
        if(x == false){
            jBtGerUsuarios.setEnabled(false);
        } else{
            jBtGerUsuarios.setEnabled(true);
        }
    }
    
    //Pega nome do Usuário, e inclui na TelaInicial
    public void bemVindo(){
        jLabelNomeExib.setText(jLabelNome.getText());
    }
    
    //Exibi a tabela da TelaUsuarios
    public void listarTabela(){
        DefaultTableModel valor = (DefaultTableModel) jTableUsuarios.getModel();
        
        valor.getDataVector().removeAllElements();
        UsuarioDAO usDAO = new UsuarioDAO();
        
        List<Usuario> usuarios = usDAO.listarTodos();
        int i = 0;
        while (usuarios.size() > i){
        
            valor.addRow(new Object[]{String.valueOf(usuarios.get(i).getId_usuario()), usuarios.get(i).getNome(),
            usuarios.get(i).getCpf(), usuarios.get(i).getEmail(), usuarios.get(i).getLogin(), usuarios.get(i).getSenha(),
            usuarios.get(i).getCargo()});
            i++;
            
        }
    }
    
    //Limpa os campos de Cadastro de Usuários     
    public void limparCamposCad(){
        jTxtNome.setText("");
        jTxtCpf.setText("");
        jTxtEmail.setText("");
        jTxtLogin.setText("");
        jPassSenha.setText("");
        jCbCargo.setSelectedItem("-");
    }
    
    //Limpa os campos de Alt/Del Usuários
    public void limparCamposAltDel(){
        jTxtAltDelId.setText("");
        jTxtAltDelNome.setText("");
        jTxtAltDelCpf.setText("");
        jTxtAltDelEmail.setText("");
        jTxtAltDelLogin.setText("");
        jTxtAltDelSenha.setText("");
        jCbAltDelCargo.setSelectedItem("-");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGPesquisa = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelCargo = new javax.swing.JLabel();
        jBtSair = new javax.swing.JButton();
        jBtGerUsuarios = new javax.swing.JButton();
        jBtGerClientes = new javax.swing.JButton();
        jBtGerLivros = new javax.swing.JButton();
        jBtGerAlugueis = new javax.swing.JButton();
        jBtHome = new javax.swing.JButton();
        jPanelFather = new javax.swing.JPanel();
        jPanelHome = new javax.swing.JPanel();
        jLabelNomeExib = new javax.swing.JLabel();
        jLabelImgExib = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanelGerUsuarios = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTxtLogin = new javax.swing.JTextField();
        jPassSenha = new javax.swing.JPasswordField();
        jLabel19 = new javax.swing.JLabel();
        jBtCadastrar = new javax.swing.JButton();
        jBtLimpar = new javax.swing.JButton();
        jTxtNome = new javax.swing.JTextField();
        jTxtEmail = new javax.swing.JTextField();
        jTxtCpf = new javax.swing.JFormattedTextField();
        jCbCargo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTxtAltDelId = new javax.swing.JTextField();
        jTxtAltDelNome = new javax.swing.JTextField();
        jTxtAltDelCpf = new javax.swing.JFormattedTextField();
        jTxtAltDelLogin = new javax.swing.JTextField();
        jTxtAltDelSenha = new javax.swing.JTextField();
        jTxtAltDelEmail = new javax.swing.JTextField();
        jCbAltDelCargo = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jRbId = new javax.swing.JRadioButton();
        jRbLogin = new javax.swing.JRadioButton();
        jTxtPesqId = new javax.swing.JTextField();
        jTxtPesqLogin = new javax.swing.JTextField();
        jBtPesquisar = new javax.swing.JButton();
        jBtAlterar = new javax.swing.JButton();
        jBtExcluir = new javax.swing.JButton();
        jPanelGerCliente = new javax.swing.JPanel();
        jPanelGerLivros = new javax.swing.JPanel();
        jPanelGerAlugueis = new javax.swing.JPanel();
        jBtLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jLabel1.setText("Dados Pessoais:");

        jLabel5.setText("ID:");

        jLabelId.setText("jLabelId");

        jLabel2.setText("Nome:");

        jLabelNome.setText("jLabelNome");

        jLabel7.setText("Login:");

        jLabelLogin.setText("jLabelLogin");

        jLabel3.setText("CPF:");

        jLabelCpf.setText("jLabelCpf");

        jLabel4.setText("E-mail:");

        jLabelEmail.setText("jLabelEmail");

        jLabel6.setText("Cargo:");

        jLabelCargo.setText("jLabelCargo");

        jBtSair.setText("Sair");
        jBtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSairActionPerformed(evt);
            }
        });

        jBtGerUsuarios.setText("Gerenciar Usuários");
        jBtGerUsuarios.setFocusable(false);
        jBtGerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtGerUsuariosActionPerformed(evt);
            }
        });

        jBtGerClientes.setText("Gerenciar Clientes");
        jBtGerClientes.setFocusable(false);
        jBtGerClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtGerClientesActionPerformed(evt);
            }
        });

        jBtGerLivros.setText("Gerenciar Livros");
        jBtGerLivros.setFocusable(false);
        jBtGerLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtGerLivrosActionPerformed(evt);
            }
        });

        jBtGerAlugueis.setText("Gerenciar Aluguéis");
        jBtGerAlugueis.setFocusable(false);
        jBtGerAlugueis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtGerAlugueisActionPerformed(evt);
            }
        });

        jBtHome.setText("Home");
        jBtHome.setFocusable(false);
        jBtHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtHomeActionPerformed(evt);
            }
        });

        jPanelFather.setBackground(new java.awt.Color(153, 153, 153));
        jPanelFather.setLayout(new java.awt.CardLayout());

        jPanelHome.setBackground(new java.awt.Color(0, 0, 102));
        jPanelHome.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNomeExib.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNomeExib.setForeground(new java.awt.Color(255, 0, 0));
        jLabelNomeExib.setText("jLabelNomeExib");

        jLabelImgExib.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Seja Bem-Vindo");

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(jLabel11))
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabelNomeExib))
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabelImgExib, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(281, Short.MAX_VALUE))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImgExib, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNomeExib)
                .addContainerGap(565, Short.MAX_VALUE))
        );

        jPanelFather.add(jPanelHome, "TelaInicial");

        jPanelGerUsuarios.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel8.setText("Alterar / Deletar Usuários:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Nome:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("CPF: ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("E-mail:");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell", 1, 12))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Login:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Senha:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jPassSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTxtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jPassSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Cargo:");

        jBtCadastrar.setText("Cadastrar");
        jBtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCadastrarActionPerformed(evt);
            }
        });

        jBtLimpar.setText("Limpar Campos");
        jBtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLimparActionPerformed(evt);
            }
        });

        try {
            jTxtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jCbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "E-mail", "Login", "Senha", "Cargo"
            }
        ));
        jTableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUsuarios);

        jLabel13.setFont(new java.awt.Font("Rockwell", 1, 16)); // NOI18N
        jLabel13.setText("Cadastro de Usuários:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Nome:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("CPF: ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("E-mail:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Login:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Senha:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Cargo:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Id:");

        jTxtAltDelId.setEditable(false);

        try {
            jTxtAltDelCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jCbAltDelCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel27.setText("Realizar pesquisa por:");

        bGPesquisa.add(jRbId);
        jRbId.setText("CPF");

        bGPesquisa.add(jRbLogin);
        jRbLogin.setText("Login");

        jBtPesquisar.setText("Pesquisar");
        jBtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRbLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtPesquisar)
                            .addComponent(jTxtPesqLogin)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRbId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtPesqId, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel27)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRbId)
                    .addComponent(jTxtPesqId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRbLogin)
                    .addComponent(jTxtPesqLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBtPesquisar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jBtAlterar.setText("Alterar");
        jBtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAlterarActionPerformed(evt);
            }
        });

        jBtExcluir.setText("Excluir");
        jBtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGerUsuariosLayout = new javax.swing.GroupLayout(jPanelGerUsuarios);
        jPanelGerUsuarios.setLayout(jPanelGerUsuariosLayout);
        jPanelGerUsuariosLayout.setHorizontalGroup(
            jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel13))
                    .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel8))
                    .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                                        .addComponent(jBtCadastrar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtLimpar))
                                    .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                                        .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGerUsuariosLayout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel19)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCbCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                                .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                                        .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                                                .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                                                        .addComponent(jLabel17)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jTxtAltDelId, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(153, 153, 153))
                                                    .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                                                        .addComponent(jLabel15)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jTxtAltDelCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(90, 90, 90)))
                                                .addComponent(jLabel25))
                                            .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel24)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTxtAltDelLogin)
                                            .addComponent(jTxtAltDelSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                                    .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                                        .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jBtAlterar)
                                            .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                                                .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                                                        .addComponent(jLabel26)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jCbAltDelCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jTxtAltDelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                                                            .addComponent(jLabel16)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(jTxtAltDelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(53, 53, 53)))
                                        .addGap(62, 62, 62)
                                        .addComponent(jBtExcluir)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addGap(0, 0, 0))
        );
        jPanelGerUsuariosLayout.setVerticalGroup(
            jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                        .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jTxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(jCbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jTxtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtLimpar)
                            .addComponent(jBtCadastrar))))
                .addGap(36, 36, 36)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTxtAltDelId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTxtAltDelNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(jTxtAltDelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTxtAltDelCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jTxtAltDelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTxtAltDelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jCbAltDelCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(jPanelGerUsuariosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanelGerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtAlterar)
                    .addComponent(jBtExcluir))
                .addGap(24, 24, 24))
        );

        jPanelFather.add(jPanelGerUsuarios, "TelaUsuarios");

        jPanelGerCliente.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanelGerClienteLayout = new javax.swing.GroupLayout(jPanelGerCliente);
        jPanelGerCliente.setLayout(jPanelGerClienteLayout);
        jPanelGerClienteLayout.setHorizontalGroup(
            jPanelGerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );
        jPanelGerClienteLayout.setVerticalGroup(
            jPanelGerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
        );

        jPanelFather.add(jPanelGerCliente, "TelaClientes");

        jPanelGerLivros.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jPanelGerLivrosLayout = new javax.swing.GroupLayout(jPanelGerLivros);
        jPanelGerLivros.setLayout(jPanelGerLivrosLayout);
        jPanelGerLivrosLayout.setHorizontalGroup(
            jPanelGerLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );
        jPanelGerLivrosLayout.setVerticalGroup(
            jPanelGerLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
        );

        jPanelFather.add(jPanelGerLivros, "TelaLivros");

        jPanelGerAlugueis.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanelGerAlugueisLayout = new javax.swing.GroupLayout(jPanelGerAlugueis);
        jPanelGerAlugueis.setLayout(jPanelGerAlugueisLayout);
        jPanelGerAlugueisLayout.setHorizontalGroup(
            jPanelGerAlugueisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );
        jPanelGerAlugueisLayout.setVerticalGroup(
            jPanelGerAlugueisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
        );

        jPanelFather.add(jPanelGerAlugueis, "TelaAlugueis");

        jBtLogOut.setText("LogOut");
        jBtLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5)
                        .addGap(25, 25, 25)
                        .addComponent(jLabelId))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7)
                        .addGap(10, 10, 10)
                        .addComponent(jLabelLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCpf))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addGap(11, 11, 11)
                        .addComponent(jLabelEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCargo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtHome, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jBtGerUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtGerClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtGerLivros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBtGerAlugueis, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jBtSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelFather, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabelId))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelNome))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabelLogin))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabelCpf))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabelEmail))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabelCargo))
                .addGap(52, 52, 52)
                .addComponent(jBtHome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtGerUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtGerClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtGerLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtGerAlugueis, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtLogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtSair)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFather, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Quando clicado no Botão Gerenciar Clientes, chama a TelaClientes
    private void jBtGerClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtGerClientesActionPerformed
        CardLayout cl = (CardLayout) jPanelFather.getLayout();
        cl.show(jPanelFather, "TelaClientes");
    }//GEN-LAST:event_jBtGerClientesActionPerformed

    //Quando clicado no Botão Gerenciar Usuarios, chama a TelaUsuarios
    private void jBtGerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtGerUsuariosActionPerformed
        CardLayout cl = (CardLayout) jPanelFather.getLayout();
        cl.show(jPanelFather, "TelaUsuarios");
    }//GEN-LAST:event_jBtGerUsuariosActionPerformed

    //Quando clicado no Botão Sair, o programa é Encerrado
    private void jBtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtSairActionPerformed

    //Cadastro de Usuário
    private void jBtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCadastrarActionPerformed
        Usuario us = new Usuario();
        us.setNome(jTxtNome.getText());
        us.setCpf(jTxtCpf.getText());
        us.setEmail(jTxtEmail.getText());
        us.setLogin(jTxtLogin.getText());
        us.setSenha(jPassSenha.getText());
        us.setCargo(String.valueOf(jCbCargo.getSelectedItem()));
        
        UsuarioDAO usDAO = new UsuarioDAO();
        usDAO.salvar(us);
        JOptionPane.showMessageDialog(null, "Usuario "+us.getNome()+" cadastrado!");
        
        limparCamposCad();
        listarTabela();
    }//GEN-LAST:event_jBtCadastrarActionPerformed

    //Alteração de Cadastro de Usuário
    private void jBtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAlterarActionPerformed
        Usuario us = new Usuario();
        us.setId_usuario(Integer.parseInt(jTxtAltDelId.getText()));
        us.setNome(jTxtAltDelNome.getText());
        us.setCpf(jTxtAltDelCpf.getText());
        us.setEmail(jTxtAltDelEmail.getText());
        us.setLogin(jTxtAltDelLogin.getText());
        us.setSenha(jTxtAltDelSenha.getText());
        us.setCargo(String.valueOf(jCbAltDelCargo.getSelectedItem()));
        
        UsuarioDAO usDAO = new UsuarioDAO();
        usDAO.alterar(us);
        JOptionPane.showMessageDialog(null, "Usuário alterado!");
        
        limparCamposAltDel();
        listarTabela();
    }//GEN-LAST:event_jBtAlterarActionPerformed

    //Pesquisa de Usuários na Tabela
    private void jBtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesquisarActionPerformed
        UsuarioDAO usDAO = new UsuarioDAO();
        List<Usuario> usuarios = null;
        
        if(jRbId.isSelected()){
            usuarios = usDAO.pesquisa(1, jTxtPesqId.getText());
        } else if(jRbLogin.isSelected()){
            usuarios = usDAO.pesquisa(2, jTxtPesqLogin.getText());
        }
        
        DefaultTableModel valor = (DefaultTableModel) jTableUsuarios.getModel();
        valor.getDataVector().removeAllElements();

        int i = 0;
        while (usuarios.size() > i){
        
            valor.addRow(new Object[]{String.valueOf(usuarios.get(i).getId_usuario()), usuarios.get(i).getNome(),
            usuarios.get(i).getCpf(), usuarios.get(i).getEmail(), usuarios.get(i).getLogin(), usuarios.get(i).getSenha(),
            usuarios.get(i).getCargo()});
            i++;
        }
    }//GEN-LAST:event_jBtPesquisarActionPerformed
    
    //Quando clicado sobre um Usuário na tabela, seus dados são inseridos nos jTextField correspondente
    private void jTableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuariosMouseClicked
        jTxtAltDelId.setText((String) jTableUsuarios.getModel().getValueAt(jTableUsuarios.getSelectedRow(), 0));
        jTxtAltDelNome.setText((String) jTableUsuarios.getModel().getValueAt(jTableUsuarios.getSelectedRow(), 1));
        jTxtAltDelCpf.setText((String) jTableUsuarios.getModel().getValueAt(jTableUsuarios.getSelectedRow(), 2));
        jTxtAltDelEmail.setText((String) jTableUsuarios.getModel().getValueAt(jTableUsuarios.getSelectedRow(), 3));
        jTxtAltDelLogin.setText((String) jTableUsuarios.getModel().getValueAt(jTableUsuarios.getSelectedRow(), 4));
        jTxtAltDelSenha.setText((String) jTableUsuarios.getModel().getValueAt(jTableUsuarios.getSelectedRow(), 5));
        jCbAltDelCargo.setSelectedItem((String) jTableUsuarios.getModel().getValueAt(jTableUsuarios.getSelectedRow(), 6));
    }//GEN-LAST:event_jTableUsuariosMouseClicked

    //Exclusão de Usuário
    private void jBtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtExcluirActionPerformed
        Usuario us = new Usuario();
        us.setId_usuario(Integer.parseInt(jTxtAltDelId.getText()));
        
        UsuarioDAO usDAO = new UsuarioDAO();
        usDAO.deletar(us);
        JOptionPane.showMessageDialog(null, "Usuário deletado");
        
        limparCamposAltDel();
        listarTabela();
    }//GEN-LAST:event_jBtExcluirActionPerformed

    //Limpar campos de Cadastro de Usuários
    private void jBtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtLimparActionPerformed
        limparCamposCad();
    }//GEN-LAST:event_jBtLimparActionPerformed

    //Quando clicado no Botão Gerenciar Livros, chama a TelaLivros
    private void jBtGerLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtGerLivrosActionPerformed
        CardLayout cl = (CardLayout) jPanelFather.getLayout();
        cl.show(jPanelFather, "TelaLivros");
    }//GEN-LAST:event_jBtGerLivrosActionPerformed
    
    //Quando clicado no Botão Gerenciar Alugueis, chama a TelaAlugueis
    private void jBtGerAlugueisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtGerAlugueisActionPerformed
        CardLayout cl = (CardLayout) jPanelFather.getLayout();
        cl.show(jPanelFather, "TelaAlugueis");
    }//GEN-LAST:event_jBtGerAlugueisActionPerformed

    //Quando clicado no Botão Home, chama a TelaInicial
    private void jBtHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtHomeActionPerformed
        CardLayout cl = (CardLayout) jPanelFather.getLayout();
        cl.show(jPanelFather, "TelaInicial");
    }//GEN-LAST:event_jBtHomeActionPerformed

    private void jBtLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtLogOutActionPerformed
        Login lg = new Login();
        lg.show();
        lg.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jBtLogOutActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGPesquisa;
    private javax.swing.JButton jBtAlterar;
    private javax.swing.JButton jBtCadastrar;
    private javax.swing.JButton jBtExcluir;
    private javax.swing.JButton jBtGerAlugueis;
    private javax.swing.JButton jBtGerClientes;
    private javax.swing.JButton jBtGerLivros;
    private javax.swing.JButton jBtGerUsuarios;
    private javax.swing.JButton jBtHome;
    private javax.swing.JButton jBtLimpar;
    private javax.swing.JButton jBtLogOut;
    private javax.swing.JButton jBtPesquisar;
    private javax.swing.JButton jBtSair;
    private javax.swing.JComboBox<String> jCbAltDelCargo;
    private javax.swing.JComboBox<String> jCbCargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCargo;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelImgExib;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNomeExib;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelFather;
    private javax.swing.JPanel jPanelGerAlugueis;
    private javax.swing.JPanel jPanelGerCliente;
    private javax.swing.JPanel jPanelGerLivros;
    private javax.swing.JPanel jPanelGerUsuarios;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPasswordField jPassSenha;
    private javax.swing.JRadioButton jRbId;
    private javax.swing.JRadioButton jRbLogin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuarios;
    private javax.swing.JFormattedTextField jTxtAltDelCpf;
    private javax.swing.JTextField jTxtAltDelEmail;
    private javax.swing.JTextField jTxtAltDelId;
    private javax.swing.JTextField jTxtAltDelLogin;
    private javax.swing.JTextField jTxtAltDelNome;
    private javax.swing.JTextField jTxtAltDelSenha;
    private javax.swing.JFormattedTextField jTxtCpf;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtLogin;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtPesqId;
    private javax.swing.JTextField jTxtPesqLogin;
    // End of variables declaration//GEN-END:variables
}
