/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import CustomClass.ManipularImagem;
import DAO.LivroDAO;
import biblioteca.Livro;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kener_000
 */
public class listarLivro extends javax.swing.JFrame {
    
    Livro selbook;
    
    public listarLivro() {
        initComponents();
        iniciarTabela();
    }
    
    public void iniciarTabela(){
        
        DefaultTableModel valor = (DefaultTableModel) jTablePesquisa.getModel();
        valor.getDataVector().removeAllElements();
        
        List<Livro> livros = new ArrayList<Livro>();
        LivroDAO livroDAO = new LivroDAO();
        
        livros = livroDAO.getTodos();
        valor.getDataVector().removeAllElements();

        int i = 0;
        while (livros.size() > i){
            valor.addRow(new Object[]{String.valueOf(livros.get(i).getId_Livro()), 
            livros.get(i).getNome(), livros.get(i).getOPT_nm_autor(), livros.get(i).getOPT_nm_categoria()});
            i++;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPesquisa = new javax.swing.ButtonGroup();
        jPanelfather = new javax.swing.JPanel();
        jPanelPesquisa = new javax.swing.JPanel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioButtonID = new javax.swing.JRadioButton();
        jRadioButtonNome = new javax.swing.JRadioButton();
        jRadioButtonAutor = new javax.swing.JRadioButton();
        jRadioButtonCat = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisa = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanelAlterar = new javax.swing.JPanel();
        jTextFieldNomeLivro = new javax.swing.JTextField();
        jLabelNomeLivro = new javax.swing.JLabel();
        jLabelQuantidadeLivro = new javax.swing.JLabel();
        jTextFieldQuantidadeLivro = new javax.swing.JTextField();
        jLabelDataLivro = new javax.swing.JLabel();
        jFormattedTextFieldDataLivro = new javax.swing.JFormattedTextField();
        jTextFieldQualidadeLivro = new javax.swing.JTextField();
        jLabelQualidadeLivro = new javax.swing.JLabel();
        jLabelResumoLivro = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaResumoLivro = new javax.swing.JTextArea();
        jButtonAddCapa = new javax.swing.JButton();
        jLabelImagemCapa = new javax.swing.JLabel();
        jLabelCapa = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa e Alteração");
        setLocation(new java.awt.Point(500, 300));
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setName("listarLivro"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelfather.setLayout(new java.awt.CardLayout());

        jPanelPesquisa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyPressed(evt);
            }
        });
        jPanelPesquisa.add(jTextFieldPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 250, -1));

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelPesquisa.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 10, 120, -1));

        buttonGroupPesquisa.add(jRadioButtonID);
        jRadioButtonID.setText("ID");
        jPanelPesquisa.add(jRadioButtonID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        buttonGroupPesquisa.add(jRadioButtonNome);
        jRadioButtonNome.setSelected(true);
        jRadioButtonNome.setText("Nome");
        jPanelPesquisa.add(jRadioButtonNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        buttonGroupPesquisa.add(jRadioButtonAutor);
        jRadioButtonAutor.setText("Autor");
        jPanelPesquisa.add(jRadioButtonAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        buttonGroupPesquisa.add(jRadioButtonCat);
        jRadioButtonCat.setText("Categoria");
        jPanelPesquisa.add(jRadioButtonCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jTablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Autor", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePesquisa);
        if (jTablePesquisa.getColumnModel().getColumnCount() > 0) {
            jTablePesquisa.getColumnModel().getColumn(0).setPreferredWidth(2);
            jTablePesquisa.getColumnModel().getColumn(3).setPreferredWidth(5);
        }

        jPanelPesquisa.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 380, 180));

        jButton2.setText("Aterar Selecionado");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanelPesquisa.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 140, -1));

        jButton3.setText("Remover Selecionado");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanelPesquisa.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanelPesquisa.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 80, -1));

        jPanelfather.add(jPanelPesquisa, "pesquisar");

        jPanelAlterar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldNomeLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeLivroActionPerformed(evt);
            }
        });
        jTextFieldNomeLivro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNomeLivroKeyPressed(evt);
            }
        });
        jPanelAlterar.add(jTextFieldNomeLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 250, -1));

        jLabelNomeLivro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNomeLivro.setText("Nome:");
        jPanelAlterar.add(jLabelNomeLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, 60, 30));

        jLabelQuantidadeLivro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelQuantidadeLivro.setText("Quantidade:");
        jPanelAlterar.add(jLabelQuantidadeLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 83, 80, 20));

        jTextFieldQuantidadeLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantidadeLivroActionPerformed(evt);
            }
        });
        jPanelAlterar.add(jTextFieldQuantidadeLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 50, -1));

        jLabelDataLivro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDataLivro.setText("Data de Publicação:");
        jPanelAlterar.add(jLabelDataLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 130, 20));

        jFormattedTextFieldDataLivro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jPanelAlterar.add(jFormattedTextFieldDataLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 42, 110, -1));

        jTextFieldQualidadeLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQualidadeLivroActionPerformed(evt);
            }
        });
        jPanelAlterar.add(jTextFieldQualidadeLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 90, -1));

        jLabelQualidadeLivro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelQualidadeLivro.setText("Qualidade:");
        jPanelAlterar.add(jLabelQualidadeLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, 80, 40));

        jLabelResumoLivro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelResumoLivro.setText("Resumo:");
        jPanelAlterar.add(jLabelResumoLivro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 30));

        jTextAreaResumoLivro.setColumns(20);
        jTextAreaResumoLivro.setRows(5);
        jScrollPane2.setViewportView(jTextAreaResumoLivro);

        jPanelAlterar.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 300, 140));

        jButtonAddCapa.setText("Nova Capa");
        jButtonAddCapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCapaActionPerformed(evt);
            }
        });
        jPanelAlterar.add(jButtonAddCapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 9, 90, 22));

        jLabelImagemCapa.setBackground(new java.awt.Color(188, 188, 188));
        jLabelImagemCapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImagemCapaMouseClicked(evt);
            }
        });
        jPanelAlterar.add(jLabelImagemCapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -60, -1, -1));
        jPanelAlterar.add(jLabelCapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 35, 80, 110));

        jButton5.setText("Salvar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanelAlterar.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 160, 80, -1));

        jButton6.setText("Cancelar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanelAlterar.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 210, 80, -1));

        jButton7.setText("Voltar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanelAlterar.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 260, 80, -1));

        jPanelfather.add(jPanelAlterar, "alterar");

        getContentPane().add(jPanelfather, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeLivroActionPerformed

    private void jTextFieldQualidadeLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQualidadeLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQualidadeLivroActionPerformed
    
    private void jButtonAddCapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCapaActionPerformed
            
        javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
        int res = fc.showOpenDialog(null);

        if (res == fc.APPROVE_OPTION) {
            File arquivo = fc.getSelectedFile();

            try {
                BufferedImage imagemBanco = ManipularImagem.setImagemDimensao(arquivo.getAbsolutePath(), 210, 260);
                BufferedImage imagemPreview = ManipularImagem.setImagemDimensao(arquivo.getAbsolutePath(), 80, 110);

                jLabelCapa.setIcon(new ImageIcon(imagemPreview));
                byte[] imagemSalvar = ManipularImagem.getImgBytes(imagemBanco);
                this.selbook.setCapa(imagemSalvar);

            } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, "Erro: "+ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Voce não selecionou nenhum arquivo.");

        }

        
        
    }//GEN-LAST:event_jButtonAddCapaActionPerformed

    private void jLabelImagemCapaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImagemCapaMouseClicked


    }//GEN-LAST:event_jLabelImagemCapaMouseClicked

    private void jTextFieldQuantidadeLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuantidadeLivroActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if(jTablePesquisa.getSelectedRow() == -1){
            
            JOptionPane.showMessageDialog(null, "Você precisa selecionar um Livro para fazer Isso!");
            
        } else {
            LivroDAO livroDAO = new LivroDAO();
            String id = (String) jTablePesquisa.getModel().getValueAt(jTablePesquisa.getSelectedRow(), 0);
            this.selbook = livroDAO.pesquisaPorID(parseInt(id));
            

            jTextFieldNomeLivro.setText(selbook.getNome());
            jFormattedTextFieldDataLivro.setText(selbook.getData());
            jTextFieldQualidadeLivro.setText(selbook.getQualidade());
            jTextFieldQuantidadeLivro.setText(String.valueOf(selbook.getQuantidade()));
            jTextAreaResumoLivro.setText(selbook.getResumo());
            
           
           
            
            ManipularImagem.exibirImagemLabel(selbook.getCapa(), jLabelCapa, 80, 110);
            
            
            CardLayout cl = (CardLayout) jPanelfather.getLayout();
            cl.show(jPanelfather, "alterar");}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        CardLayout cl = (CardLayout) jPanelfather.getLayout();
        cl.show(jPanelfather, "pesquisar");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(jTextFieldPesquisa.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Você precisa Digitar algo para Pesquisar!");   
        } else {
            
            List<Livro> livros = new ArrayList<Livro>();
            if(jRadioButtonID.isSelected()) {
                LivroDAO livroDAO = new LivroDAO();
                
                Livro livro = new Livro();
                
                livro = livroDAO.pesquisaPorID(parseInt(jTextFieldPesquisa.getText()));
                livros.add(livro);
            } 
            if(jRadioButtonNome.isSelected()) {
                LivroDAO livroDAO = new LivroDAO();
                livros = livroDAO.pesquisa("Nome", jTextFieldPesquisa.getText());     
            }
            if(jRadioButtonAutor.isSelected()){
                LivroDAO livroDAO = new LivroDAO();
                
                livros = livroDAO.pesquisa("Autor", jTextFieldPesquisa.getText()); 
            }
            if(jRadioButtonCat.isSelected()){
                LivroDAO livroDAO = new LivroDAO();
                
                livros = livroDAO.pesquisa("Categoria", jTextFieldPesquisa.getText());
            }
            
            DefaultTableModel valor = (DefaultTableModel) jTablePesquisa.getModel();
            valor.getDataVector().removeAllElements();
            
            int i = 0;
            while (livros.size() > i){
                valor.addRow(new Object[]{String.valueOf(livros.get(i).getId_Livro()), 
                livros.get(i).getNome(), livros.get(i).getOPT_nm_autor(), livros.get(i).getOPT_nm_categoria()});
                i++;
        }
            
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            
        if(jTextFieldNomeLivro.getText().isBlank() || jTextFieldQuantidadeLivro.getText().isBlank()
            ){
            
            JOptionPane.showMessageDialog(null, "Negado! Faltam Campos Essenciais a Serem Preenchidos!");
        
        }else{
            try{
            selbook.setNome(jTextFieldNomeLivro.getText());
            selbook.setQuantidade( parseInt(jTextFieldQuantidadeLivro.getText()));
            selbook.setData(jFormattedTextFieldDataLivro.getText());
            selbook.setQualidade(jTextFieldQualidadeLivro.getText());
            selbook.setResumo(jTextAreaResumoLivro.getText());

            LivroDAO livroDAO = new LivroDAO();
            livroDAO.alterar(selbook);

            JOptionPane.showMessageDialog(null, "O Livro "+selbook.getNome()+" foi Atualizado!");
            iniciarTabela();
            CardLayout cl = (CardLayout) jPanelfather.getLayout();
            cl.show(jPanelfather, "pesquisar");                         

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e+"AreaUsuario");
        }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextFieldNomeLivroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeLivroKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeLivroKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(jTablePesquisa.getSelectedRow() == -1){
            
            JOptionPane.showMessageDialog(null, "Você precisa selecionar um Livro para fazer Isso!");
            
        } else {
            LivroDAO livroDAO = new LivroDAO();
            String id = (String) jTablePesquisa.getModel().getValueAt(jTablePesquisa.getSelectedRow(), 0);
            this.selbook = livroDAO.pesquisaPorID(parseInt(id));
            
            livroDAO.remover(selbook);
            selbook = null;
            iniciarTabela();
                       
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyPressed
            if(evt.getKeyCode()== KeyEvent.VK_ENTER){
                
                       if(jTextFieldPesquisa.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Você precisa Digitar algo para Pesquisar!");   
        } else {
            
            List<Livro> livros = new ArrayList<Livro>();
            if(jRadioButtonID.isSelected()) {
                LivroDAO livroDAO = new LivroDAO();
                
                Livro livro = new Livro();
                
                livro = livroDAO.pesquisaPorID(parseInt(jTextFieldPesquisa.getText()));
                livros.add(livro);
            } 
            if(jRadioButtonNome.isSelected()) {
                LivroDAO livroDAO = new LivroDAO();
                livros = livroDAO.pesquisa("Nome", jTextFieldPesquisa.getText());     
            }
            if(jRadioButtonAutor.isSelected()){
                LivroDAO livroDAO = new LivroDAO();
                
                livros = livroDAO.pesquisa("Autor", jTextFieldPesquisa.getText()); 
            }
            if(jRadioButtonCat.isSelected()){
                LivroDAO livroDAO = new LivroDAO();
                
                livros = livroDAO.pesquisa("Categoria", jTextFieldPesquisa.getText());
            }
            
            DefaultTableModel valor = (DefaultTableModel) jTablePesquisa.getModel();
            valor.getDataVector().removeAllElements();
            
            int i = 0;
            while (livros.size() > i){
                valor.addRow(new Object[]{String.valueOf(livros.get(i).getId_Livro()), 
                livros.get(i).getNome(), livros.get(i).getOPT_nm_autor(), livros.get(i).getOPT_nm_categoria()});
                i++;
        }
            
        }
                
            }
    }//GEN-LAST:event_jTextFieldPesquisaKeyPressed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listarLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupPesquisa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonAddCapa;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataLivro;
    private javax.swing.JLabel jLabelCapa;
    private javax.swing.JLabel jLabelDataLivro;
    private javax.swing.JLabel jLabelImagemCapa;
    private javax.swing.JLabel jLabelNomeLivro;
    private javax.swing.JLabel jLabelQualidadeLivro;
    private javax.swing.JLabel jLabelQuantidadeLivro;
    private javax.swing.JLabel jLabelResumoLivro;
    private javax.swing.JPanel jPanelAlterar;
    private javax.swing.JPanel jPanelPesquisa;
    private javax.swing.JPanel jPanelfather;
    private javax.swing.JRadioButton jRadioButtonAutor;
    private javax.swing.JRadioButton jRadioButtonCat;
    private javax.swing.JRadioButton jRadioButtonID;
    private javax.swing.JRadioButton jRadioButtonNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePesquisa;
    private javax.swing.JTextArea jTextAreaResumoLivro;
    private javax.swing.JTextField jTextFieldNomeLivro;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldQualidadeLivro;
    private javax.swing.JTextField jTextFieldQuantidadeLivro;
    // End of variables declaration//GEN-END:variables
}
