package view;

import CustomClass.RoundedPanel;
import DAO.ClienteDAO;
import DAO.UsuarioDAO;
import biblioteca.Cliente;
import biblioteca.Usuario;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {
    
    public Login() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new RoundedPanel(30);
        jPanelLogin = new RoundedPanel(30);
        jTxtLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPassSenha = new javax.swing.JPasswordField();
        jButtonEntrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setUndecorated(true);
        setResizable(false);
        setShape(new RoundRectangle2D.Double(0,0, 390, 173, 40,40));

        jPanel2.setBackground(new java.awt.Color(37, 37, 37));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLogin.setBackground(new java.awt.Color(37, 37, 37));
        jPanelLogin.setForeground(new java.awt.Color(255, 255, 255));
        jPanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelLogin.add(jTxtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 206, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Login:  ");
        jPanelLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Senha:");
        jPanelLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jPassSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPassSenhaKeyPressed(evt);
            }
        });
        jPanelLogin.add(jPassSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 207, -1));

        jButtonEntrar.setBackground(new java.awt.Color(67, 67, 67));
        jButtonEntrar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButtonEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.setAlignmentY(-0.5F);
        jButtonEntrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEntrar.setOpaque(false);
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 92, 80, 30));

        jPanel2.add(jPanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 24, 360, 130));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Efetue seu Login");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 4, -1, -1));

        jPanel1.setOpaque(false);
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 30, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Realiza as devidas validações e chama a Tela correspondente
    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed

            UsuarioDAO us = new UsuarioDAO();
            ClienteDAO clt = new ClienteDAO();
            Usuario usuario = new Usuario();
            Cliente cliente = new Cliente();
            
            //Realiza a validação de Usuário
            if(us.validarLoginUsuario(jTxtLogin.getText(), jPassSenha.getText()) == true){
                usuario.setLogin(jTxtLogin.getText());
                AreaUsuario au = new AreaUsuario();
                au.setUsLogin(usuario);
                au.validaAdm(us.validarAdm(jTxtLogin.getText()));
                au.bemVindo();
                au.setResizable(false);
                au.show();
                au.setLocationRelativeTo(null);
                
            //Realiza a validação de Cliente
            } else if(clt.validarLoginCliente(jTxtLogin.getText(), jPassSenha.getText()) == true){
                cliente.setLogin(jTxtLogin.getText());
                AreaCliente ac = new AreaCliente();
                ac.show();
                ac.setLocationRelativeTo(null);
                ac.setCltLogin(cliente);
                ac.bemVindo();
                
            } else{
                JOptionPane.showMessageDialog(null, "Usuário/Senha incorreto");
            }
        
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    //Depois de digitar a Senha, se apertar Enter, Login é realizado, juntamente com suas Validações
    private void jPassSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassSenhaKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            UsuarioDAO us = new UsuarioDAO();
            ClienteDAO clt = new ClienteDAO();
            Usuario usuario = new Usuario();
            Cliente cliente = new Cliente();
            
            //Realiza a validação de Usuário
            if(us.validarLoginUsuario(jTxtLogin.getText(), jPassSenha.getText()) == true){
                usuario.setLogin(jTxtLogin.getText());
                AreaUsuario au = new AreaUsuario();
                au.setUsLogin(usuario);
                au.validaAdm(us.validarAdm(jTxtLogin.getText()));
                au.bemVindo();
                au.setResizable(false);
                au.show();
                au.setLocationRelativeTo(null);
                
            //Realiza a validação de Cliente
            } else if(clt.validarLoginCliente(jTxtLogin.getText(), jPassSenha.getText()) == true){
                cliente.setLogin(jTxtLogin.getText());
                AreaCliente ac = new AreaCliente();
                ac.show();
                ac.setLocationRelativeTo(null);
                ac.setCltLogin(cliente);
                ac.bemVindo();
                
            } else{
                JOptionPane.showMessageDialog(null, "Usuário/Senha incorreto");
            }
        }
    }//GEN-LAST:event_jPassSenhaKeyPressed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked
        
        //Código para Mover o Frame de Login
    
    int mx;
    int my;
    
    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
      
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-mx, y-my);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
       mx = evt.getX();
       my = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPasswordField jPassSenha;
    private javax.swing.JTextField jTxtLogin;
    // End of variables declaration//GEN-END:variables
}
