/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import javax.swing.JPanel;



/**
 *
 * @author Cunhas
 */
public class TelaCardLayout extends javax.swing.JFrame {

    /**
     * Creates new form TelaCardLayout
     */
    public TelaCardLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelGerenciamento = new javax.swing.JLabel();
        jSeparatorGer = new javax.swing.JSeparator();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jLabelPesquisa = new javax.swing.JLabel();
        jSeparatorPes = new javax.swing.JSeparator();
        jButtonConteudoHistorico = new javax.swing.JButton();
        jButtonAventura = new javax.swing.JButton();
        jButtonSuspense = new javax.swing.JButton();
        jButtonTerror = new javax.swing.JButton();
        jButtonRomance = new javax.swing.JButton();
        jButtonEducacional = new javax.swing.JButton();
        jButtonComedia = new javax.swing.JButton();
        jLabelCategoria = new javax.swing.JLabel();
        jSeparatorCat = new javax.swing.JSeparator();
        jButtonPerfil = new javax.swing.JButton();
        jButtonLivrosAlugados = new javax.swing.JButton();
        jButtonHistorico = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(67, 67, 67));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelGerenciamento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelGerenciamento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGerenciamento.setText("Gerenciamento");
        jPanel1.add(jLabelGerenciamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 170, 30));
        jPanel1.add(jSeparatorGer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 170, 10));
        jPanel1.add(jTextFieldPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, 170, -1));

        jLabelPesquisa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPesquisa.setText("Pesquisa");
        jPanel1.add(jLabelPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 170, 30));
        jPanel1.add(jSeparatorPes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 170, 10));

        jButtonConteudoHistorico.setForeground(new java.awt.Color(90, 95, 98));
        jButtonConteudoHistorico.setText("Conteudo Histórico");
        jButtonConteudoHistorico.setBorderPainted(false);
        jButtonConteudoHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConteudoHistoricoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonConteudoHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 170, 20));

        jButtonAventura.setForeground(new java.awt.Color(90, 95, 98));
        jButtonAventura.setText("Aventura");
        jButtonAventura.setBorderPainted(false);
        jButtonAventura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAventuraActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAventura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 170, 20));

        jButtonSuspense.setForeground(new java.awt.Color(90, 95, 98));
        jButtonSuspense.setText("Suspense");
        jButtonSuspense.setBorderPainted(false);
        jButtonSuspense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuspenseActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSuspense, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 170, 20));

        jButtonTerror.setForeground(new java.awt.Color(90, 95, 98));
        jButtonTerror.setText("Terror");
        jButtonTerror.setBorderPainted(false);
        jButtonTerror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTerrorActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 170, 20));

        jButtonRomance.setForeground(new java.awt.Color(90, 95, 98));
        jButtonRomance.setText("Romance");
        jButtonRomance.setBorderPainted(false);
        jButtonRomance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRomanceActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRomance, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 170, 20));

        jButtonEducacional.setForeground(new java.awt.Color(90, 95, 98));
        jButtonEducacional.setText("Educacional");
        jButtonEducacional.setBorderPainted(false);
        jButtonEducacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEducacionalActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEducacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 170, 20));

        jButtonComedia.setForeground(new java.awt.Color(90, 95, 98));
        jButtonComedia.setText("Comédia");
        jButtonComedia.setBorderPainted(false);
        jButtonComedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComediaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonComedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 170, 20));

        jLabelCategoria.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCategoria.setText("Categorias");
        jPanel1.add(jLabelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 30));
        jPanel1.add(jSeparatorCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 10));

        jButtonPerfil.setForeground(new java.awt.Color(90, 95, 98));
        jButtonPerfil.setText("Meu Perfil");
        jButtonPerfil.setBorderPainted(false);
        jButtonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 170, 20));

        jButtonLivrosAlugados.setForeground(new java.awt.Color(90, 95, 98));
        jButtonLivrosAlugados.setText("Livros Alugados");
        jButtonLivrosAlugados.setActionCommand("");
        jButtonLivrosAlugados.setBorderPainted(false);
        jButtonLivrosAlugados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLivrosAlugadosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLivrosAlugados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 170, 20));

        jButtonHistorico.setForeground(new java.awt.Color(90, 95, 98));
        jButtonHistorico.setText("Histórico");
        jButtonHistorico.setBorderPainted(false);
        jPanel1.add(jButtonHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 170, 20));

        jButtonLogout.setForeground(new java.awt.Color(90, 95, 98));
        jButtonLogout.setText("Logout");
        jPanel1.add(jButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 70, 30));

        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, "telaAventura");

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, "telaSuspense");

        jPanel5.setBackground(new java.awt.Color(102, 0, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, "telaTerror");

        jPanel6.setBackground(new java.awt.Color(204, 0, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, "telaRomance");

        jPanel7.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, "telaEducacional");

        jPanel8.setBackground(new java.awt.Color(204, 51, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, "telaComedia");

        jPanel9.setBackground(new java.awt.Color(51, 204, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel9, "telaContHist");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPerfilActionPerformed

    private void jButtonLivrosAlugadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLivrosAlugadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLivrosAlugadosActionPerformed

    private void jButtonAventuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAventuraActionPerformed
        // TODO add your handling code here:
        
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "telaAventura");
        
    }//GEN-LAST:event_jButtonAventuraActionPerformed

    private void jButtonSuspenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuspenseActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "telaSuspense");
    }//GEN-LAST:event_jButtonSuspenseActionPerformed

    private void jButtonTerrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTerrorActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "telaTerror");
        
    }//GEN-LAST:event_jButtonTerrorActionPerformed

    private void jButtonRomanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRomanceActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "telaRomance");
        
    }//GEN-LAST:event_jButtonRomanceActionPerformed

    private void jButtonEducacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEducacionalActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "telaEducacional");
        
    }//GEN-LAST:event_jButtonEducacionalActionPerformed

    private void jButtonComediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComediaActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "telaComedia");
        
    }//GEN-LAST:event_jButtonComediaActionPerformed

    private void jButtonConteudoHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConteudoHistoricoActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel2.getLayout();
        cl.show(jPanel2, "telaContHist");
        
    }//GEN-LAST:event_jButtonConteudoHistoricoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCardLayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAventura;
    private javax.swing.JButton jButtonComedia;
    private javax.swing.JButton jButtonConteudoHistorico;
    private javax.swing.JButton jButtonEducacional;
    private javax.swing.JButton jButtonHistorico;
    private javax.swing.JButton jButtonLivrosAlugados;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonPerfil;
    private javax.swing.JButton jButtonRomance;
    private javax.swing.JButton jButtonSuspense;
    private javax.swing.JButton jButtonTerror;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelGerenciamento;
    private javax.swing.JLabel jLabelPesquisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparatorCat;
    private javax.swing.JSeparator jSeparatorGer;
    private javax.swing.JSeparator jSeparatorPes;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables

    }

